// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2r3KpVBseZsCoYH-_rGorrZ3nZTVEvSo',
    appId: '1:533876576717:web:1c565b63e89c5eb18ff484',
    messagingSenderId: '533876576717',
    projectId: 'connecta-1459a',
    authDomain: 'connecta-1459a.firebaseapp.com',
    storageBucket: 'connecta-1459a.appspot.com',
    measurementId: 'G-4R0Z5VE9J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWfET9CggGRHKsdwJx1bpJXLZs8cHV8jo',
    appId: '1:533876576717:android:03e0fce635cda6ea8ff484',
    messagingSenderId: '533876576717',
    projectId: 'connecta-1459a',
    storageBucket: 'connecta-1459a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jwauOex0XgjdlYfRlXjm0RVMNu33EJc',
    appId: '1:533876576717:ios:7501466eaad9f3118ff484',
    messagingSenderId: '533876576717',
    projectId: 'connecta-1459a',
    storageBucket: 'connecta-1459a.appspot.com',
    iosClientId: '533876576717-6a30t6m0afnj8j4ohrol28huob5uvrql.apps.googleusercontent.com',
    iosBundleId: 'com.example.connecta',
  );
}
